ADD_LIBRARY(LIBJINGLE_PEERCONNECTION STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBJINGLE_PEERCONNECTION PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libjingle_peerconnection.a)
ADD_LIBRARY(LIBFIELD_TRIAL_DEFAULT STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBFIELD_TRIAL_DEFAULT PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libfield_trial_default.a)
ADD_LIBRARY(LIBJSONCPP STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBJSONCPP PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libjsoncpp.a)
ADD_LIBRARY(LIBRTC_BASE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_BASE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_base.a)
ADD_LIBRARY(LIBWEBRTC_COMMON STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_COMMON PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_common.a)
ADD_LIBRARY(LIBRTC_BASE_APPROVED STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_BASE_APPROVED PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_base_approved.a)
ADD_LIBRARY(LIBBORINGSSL STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBBORINGSSL PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libboringssl.a)
ADD_LIBRARY(LIBWEBRTC_UTILITY STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_UTILITY PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_utility.a)
ADD_LIBRARY(LIBAUDIO_CODING_MODULE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_CODING_MODULE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_coding_module.a)
ADD_LIBRARY(LIBCNG STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCNG PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcng.a)
ADD_LIBRARY(LIBCOMMON_AUDIO STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCOMMON_AUDIO PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcommon_audio.a)
ADD_LIBRARY(LIBSYSTEM_WRAPPERS STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBSYSTEM_WRAPPERS PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libsystem_wrappers.a)
ADD_LIBRARY(LIBOPENMAX_DL STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBOPENMAX_DL PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libopenmax_dl.a)
ADD_LIBRARY(LIBCOMMON_AUDIO_SSE2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCOMMON_AUDIO_SSE2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcommon_audio_sse2.a)
ADD_LIBRARY(LIBAUDIO_ENCODER_INTERFACE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_ENCODER_INTERFACE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_encoder_interface.a)
ADD_LIBRARY(LIBG711 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBG711 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libg711.a)
ADD_LIBRARY(LIBPCM16B STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBPCM16B PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libpcm16b.a)
ADD_LIBRARY(LIBWEBRTC_OPUS STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_OPUS PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_opus.a)
ADD_LIBRARY(LIBOPUS STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBOPUS PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libopus.a)
ADD_LIBRARY(LIBG722 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBG722 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libg722.a)
ADD_LIBRARY(LIBISAC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBISAC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libisac.a)
ADD_LIBRARY(LIBAUDIO_DECODER_INTERFACE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_DECODER_INTERFACE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_decoder_interface.a)
ADD_LIBRARY(LIBISAC_COMMON STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBISAC_COMMON PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libisac_common.a)
ADD_LIBRARY(LIBILBC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBILBC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libilbc.a)
ADD_LIBRARY(LIBRED STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRED PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libred.a)
ADD_LIBRARY(LIBRTC_EVENT_LOG STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_EVENT_LOG PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_event_log.a)
ADD_LIBRARY(LIBRTC_EVENT_LOG_PROTO STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_EVENT_LOG_PROTO PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_event_log_proto.a)
ADD_LIBRARY(LIBPROTOBUF_LITE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBPROTOBUF_LITE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libprotobuf_lite.a)
ADD_LIBRARY(LIBNETEQ STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBNETEQ PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libneteq.a)
ADD_LIBRARY(LIBRENT_A_CODEC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRENT_A_CODEC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librent_a_codec.a)
ADD_LIBRARY(LIBMEDIA_FILE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBMEDIA_FILE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libmedia_file.a)
ADD_LIBRARY(LIBCOMMON_VIDEO STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCOMMON_VIDEO PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcommon_video.a)
ADD_LIBRARY(LIBYUV STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBYUV PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libyuv.a)
ADD_LIBRARY(LIBJPEG_TURBO STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBJPEG_TURBO PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libjpeg_turbo.a)
ADD_LIBRARY(LIBWEBRTC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc.a)
ADD_LIBRARY(LIBVOICE_ENGINE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVOICE_ENGINE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvoice_engine.a)
ADD_LIBRARY(LIBAUDIO_CONFERENCE_MIXER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_CONFERENCE_MIXER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_conference_mixer.a)
ADD_LIBRARY(LIBAUDIO_PROCESSING STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_PROCESSING PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_processing.a)
ADD_LIBRARY(LIBAUDIOPROC_DEBUG_PROTO STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIOPROC_DEBUG_PROTO PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudioproc_debug_proto.a)
ADD_LIBRARY(LIBAUDIO_PROCESSING_SSE2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_PROCESSING_SSE2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_processing_sse2.a)
ADD_LIBRARY(LIBAUDIO_DEVICE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_DEVICE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_device.a)
ADD_LIBRARY(LIBBITRATE_CONTROLLER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBBITRATE_CONTROLLER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libbitrate_controller.a)
ADD_LIBRARY(LIBRTP_RTCP STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTP_RTCP PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtp_rtcp.a)
ADD_LIBRARY(LIBREMOTE_BITRATE_ESTIMATOR STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBREMOTE_BITRATE_ESTIMATOR PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libremote_bitrate_estimator.a)
ADD_LIBRARY(LIBVIDEO_CAPTURE_MODULE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_CAPTURE_MODULE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_capture_module.a)
ADD_LIBRARY(LIBVIDEO_PROCESSING STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_PROCESSING PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_processing.a)
ADD_LIBRARY(LIBVIDEO_PROCESSING_SSE2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_PROCESSING_SSE2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_processing_sse2.a)
ADD_LIBRARY(LIBWEBRTC_VIDEO_CODING STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_VIDEO_CODING PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_video_coding.a)
ADD_LIBRARY(LIBWEBRTC_H264 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_H264 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_h264.a)
ADD_LIBRARY(LIBWEBRTC_I420 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_I420 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_i420.a)
ADD_LIBRARY(LIBVIDEO_CODING_UTILITY STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_CODING_UTILITY PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_coding_utility.a)
ADD_LIBRARY(LIBWEBRTC_VP8 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_VP8 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_vp8.a)
ADD_LIBRARY(LIBVPX STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_SSE2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_SSE2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_sse2.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_SSSE3 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_SSSE3 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_ssse3.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_AVX2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_AVX2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_avx2.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_MMX STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_MMX PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_mmx.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_SSE4_1 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_SSE4_1 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_sse4_1.a)
ADD_LIBRARY(LIBWEBRTC_VP9 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBWEBRTC_VP9 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libwebrtc_vp9.a)
ADD_LIBRARY(LIBMETRICS_DEFAULT STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBMETRICS_DEFAULT PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libmetrics_default.a)
ADD_LIBRARY(LIBRTC_P2P STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_P2P PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_p2p.a)
ADD_LIBRARY(LIBUSRSCTPLIB STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBUSRSCTPLIB PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libusrsctplib.a)
# ADD_LIBRARY(LIBVIDEO_CAPTURE_MODULE_INTERNAL_IMPL STATIC IMPORTED)
# SET_TARGET_PROPERTIES(LIBVIDEO_CAPTURE_MODULE_INTERNAL_IMPL PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_capture_module_internal_impl.a)
ADD_LIBRARY(LIBSRTP STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBSRTP PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libsrtp.a)
ADD_LIBRARY(LIBBORINGSSL_ASM STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBBORINGSSL_ASM PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libboringssl_asm.a)
ADD_LIBRARY(LIBCONGESTION_CONTROLLER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCONGESTION_CONTROLLER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcongestion_controller.a)
ADD_LIBRARY(LIBRTC_PC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_PC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_pc.a)
ADD_LIBRARY(LIBRTC_MEDIA STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_MEDIA PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_media.a)
ADD_LIBRARY(LIBDESKTOP_CAPTURE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBDESKTOP_CAPTURE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libdesktop_capture.a)
ADD_LIBRARY(LIBSTUNPROBER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBSTUNPROBER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libstunprober.a)
ADD_LIBRARY(LIBRTC_EVENT_LOG_PARSER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_EVENT_LOG_PARSER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_event_log_parser.a)
ADD_LIBRARY(LIBVIDEO_QUALITY_ANALYSIS STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_QUALITY_ANALYSIS PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_quality_analysis.a)
ADD_LIBRARY(LIBCOMMAND_LINE_PARSER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBCOMMAND_LINE_PARSER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libcommand_line_parser.a)
ADD_LIBRARY(LIBFRAME_EDITING_LIB STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBFRAME_EDITING_LIB PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libframe_editing_lib.a)
ADD_LIBRARY(LIBAUDIO_DECODER_FACTORY_INTERFACE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_DECODER_FACTORY_INTERFACE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_decoder_factory_interface.a)
ADD_LIBRARY(LIBVIDEO_CAPTURE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVIDEO_CAPTURE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvideo_capture.a)
ADD_LIBRARY(LIBBUILTIN_AUDIO_DECODER_FACTORY STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBBUILTIN_AUDIO_DECODER_FACTORY PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libbuiltin_audio_decoder_factory.a)
ADD_LIBRARY(LIBPACED_SENDER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBPACED_SENDER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libpaced_sender.a)
ADD_LIBRARY(LIBDESKTOP_CAPTURE_DIFFER_SSE2 STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBDESKTOP_CAPTURE_DIFFER_SSE2 PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libdesktop_capture_differ_sse2.a)
ADD_LIBRARY(LIBISAC_FIX STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBISAC_FIX PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libisac_fix.a)
ADD_LIBRARY(LIBGENPERF_LIBS STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBGENPERF_LIBS PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libgenperf_libs.a)
ADD_LIBRARY(LIBPROTOBUF_FULL_DO_NOT_USE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBPROTOBUF_FULL_DO_NOT_USE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libprotobuf_full_do_not_use.a)
ADD_LIBRARY(LIBPROTOC_LIB STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBPROTOC_LIB PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libprotoc_lib.a)
ADD_LIBRARY(LIBVPX_INTRINSICS_AVX STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBVPX_INTRINSICS_AVX PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libvpx_intrinsics_avx.a)
ADD_LIBRARY(LIBRTC_TASK_QUEUE STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_TASK_QUEUE PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_task_queue.a)

ADD_LIBRARY(LIBAPPRTC_COMMON STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAPPRTC_COMMON PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libapprtc_common.a)
ADD_LIBRARY(LIBAPPRTC_SIGNALING STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAPPRTC_SIGNALING PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libapprtc_signaling.a)
ADD_LIBRARY(LIBAUDIO_MIXER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBAUDIO_MIXER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libaudio_mixer.a)
ADD_LIBRARY(LIBJINGLE_PEERCONNECTION_OBJC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBJINGLE_PEERCONNECTION_OBJC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libjingle_peerconnection_objc.a)
ADD_LIBRARY(LIBNEW_AUDIO_CONFERENCE_MIXER STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBNEW_AUDIO_CONFERENCE_MIXER PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libnew_audio_conference_mixer.a)
ADD_LIBRARY(LIBRTC_SDK_COMMON_OBJC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_SDK_COMMON_OBJC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_sdk_common_objc.a)
ADD_LIBRARY(LIBRTC_SDK_PEERCONNECTION_OBJC STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBRTC_SDK_PEERCONNECTION_OBJC PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/librtc_sdk_peerconnection_objc.a)
ADD_LIBRARY(LIBSOCKETROCKET STATIC IMPORTED)
SET_TARGET_PROPERTIES(LIBSOCKETROCKET PROPERTIES IMPORTED_LOCATION ${WEBRTCBUILD}/libsocketrocket.a)

SET(WEBRTC_LIBS
  PUBLIC LIBJINGLE_PEERCONNECTION
  PUBLIC LIBFIELD_TRIAL_DEFAULT
  PUBLIC LIBJSONCPP
  PUBLIC LIBRTC_BASE
  PUBLIC LIBWEBRTC_COMMON
  PUBLIC LIBRTC_BASE_APPROVED
  PUBLIC LIBBORINGSSL
  PUBLIC LIBWEBRTC_UTILITY
  PUBLIC LIBAUDIO_CODING_MODULE
  PUBLIC LIBCNG
  PUBLIC LIBCOMMON_AUDIO
  PUBLIC LIBSYSTEM_WRAPPERS
  PUBLIC LIBOPENMAX_DL
  PUBLIC LIBCOMMON_AUDIO_SSE2
  PUBLIC LIBAUDIO_ENCODER_INTERFACE
  PUBLIC LIBG711
  PUBLIC LIBPCM16B
  PUBLIC LIBWEBRTC_OPUS
  PUBLIC LIBOPUS
  PUBLIC LIBG722
  PUBLIC LIBISAC
  PUBLIC LIBAUDIO_DECODER_INTERFACE
  PUBLIC LIBISAC_COMMON
  PUBLIC LIBILBC
  PUBLIC LIBRED
  PUBLIC LIBRTC_EVENT_LOG
  PUBLIC LIBRTC_EVENT_LOG_PROTO
  PUBLIC LIBPROTOBUF_LITE
  PUBLIC LIBNETEQ
  PUBLIC LIBRENT_A_CODEC
  PUBLIC LIBMEDIA_FILE
  PUBLIC LIBCOMMON_VIDEO
  PUBLIC LIBYUV
  PUBLIC LIBJPEG_TURBO
  PUBLIC LIBWEBRTC
  PUBLIC LIBVOICE_ENGINE
  PUBLIC LIBAUDIO_CONFERENCE_MIXER
  PUBLIC LIBAUDIO_PROCESSING
  PUBLIC LIBAUDIOPROC_DEBUG_PROTO
  PUBLIC LIBAUDIO_PROCESSING_SSE2
  PUBLIC LIBAUDIO_DEVICE
  PUBLIC LIBBITRATE_CONTROLLER
  PUBLIC LIBPACED_SENDER
  PUBLIC LIBRTP_RTCP
  PUBLIC LIBREMOTE_BITRATE_ESTIMATOR
  PUBLIC LIBVIDEO_CAPTURE_MODULE
  PUBLIC LIBVIDEO_PROCESSING
  PUBLIC LIBVIDEO_PROCESSING_SSE2
  PUBLIC LIBWEBRTC_VIDEO_CODING
  PUBLIC LIBWEBRTC_H264
  PUBLIC LIBWEBRTC_I420
  PUBLIC LIBVIDEO_CODING_UTILITY
  PUBLIC LIBWEBRTC_VP8
  PUBLIC LIBVPX
  PUBLIC LIBVPX_INTRINSICS_SSE2
  PUBLIC LIBVPX_INTRINSICS_SSSE3
  PUBLIC LIBVPX_INTRINSICS_AVX2
  PUBLIC LIBVPX_INTRINSICS_MMX
  PUBLIC LIBVPX_INTRINSICS_SSE4_1
  PUBLIC LIBWEBRTC_VP9
  PUBLIC LIBMETRICS_DEFAULT
  PUBLIC LIBRTC_P2P
  PUBLIC LIBUSRSCTPLIB
  # PUBLIC LIBVIDEO_CAPTURE_MODULE_INTERNAL_IMPL
  PUBLIC LIBSRTP
  PUBLIC LIBBORINGSSL_ASM
  PUBLIC LIBCONGESTION_CONTROLLER
  PUBLIC LIBRTC_PC
  PUBLIC LIBRTC_MEDIA
  PUBLIC LIBDESKTOP_CAPTURE
  PUBLIC LIBSTUNPROBER
  PUBLIC LIBRTC_EVENT_LOG_PARSER
  PUBLIC LIBVIDEO_QUALITY_ANALYSIS
  PUBLIC LIBCOMMAND_LINE_PARSER
  PUBLIC LIBFRAME_EDITING_LIB
  PUBLIC LIBAUDIO_DECODER_FACTORY_INTERFACE
  PUBLIC LIBVIDEO_CAPTURE
  PUBLIC LIBBUILTIN_AUDIO_DECODER_FACTORY
  PUBLIC LIBPACED_SENDER
  PUBLIC LIBDESKTOP_CAPTURE_DIFFER_SSE2
  PUBLIC LIBISAC_FIX
  PUBLIC LIBGENPERF_LIBS
  PUBLIC LIBPROTOBUF_FULL_DO_NOT_USE
  PUBLIC LIBPROTOC_LIB
  PUBLIC LIBVPX_INTRINSICS_AVX
  PUBLIC LIBRTC_TASK_QUEUE
  PUBLIC LIBAPPRTC_COMMON
  PUBLIC LIBAPPRTC_SIGNALING
  PUBLIC LIBAUDIO_MIXER
  PUBLIC LIBJINGLE_PEERCONNECTION_OBJC
  PUBLIC LIBNEW_AUDIO_CONFERENCE_MIXER
  PUBLIC LIBRTC_SDK_COMMON_OBJC
  PUBLIC LIBRTC_SDK_PEERCONNECTION_OBJC
  PUBLIC LIBSOCKETROCKET
)
