SET (OBJ_DEPS 
${WEBRTCBUILD}/obj/third_party/jsoncpp/jsoncpp/json_reader.o
${WEBRTCBUILD}/obj/third_party/jsoncpp/jsoncpp/json_value.o
${WEBRTCBUILD}/obj/third_party/jsoncpp/jsoncpp/json_writer.o
${WEBRTCBUILD}/obj/webrtc/call/call_interfaces/audio_send_stream.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/fft4g.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/ring_buffer.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/auto_corr_to_refl_coef.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/auto_correlation.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/copy_set_operations.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/cross_correlation.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/division_operations.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/dot_product_with_scale.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/downsample_fast.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/energy.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/filter_ar.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/filter_ma_fast_q12.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/get_hanning_window.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/get_scaling_square.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/ilbc_specific_functions.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/levinson_durbin.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/lpc_to_refl_coef.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/min_max_operations.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/randomization_functions.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/real_fft.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/refl_coef_to_lpc.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/resample.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/resample_48khz.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/resample_by_2.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/resample_by_2_internal.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/resample_fractional.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/spl_init.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/spl_inl.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/spl_sqrt.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/splitting_filter.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/sqrt_of_one_minus_x_squared.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/vector_scaling_operations.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/vad_core.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/vad_filterbank.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/vad_gmm.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/vad_sp.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/webrtc_vad.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/complex_fft.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/complex_bit_reverse.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/filter_ar_fast_q12.o
${WEBRTCBUILD}/obj/webrtc/common_audio/common_audio_c/spl_sqrt_floor.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/webrtc_opus_c/opus_interface.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/g711_c/g711.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/g711_c/g711_interface.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/pcm16b_c/pcm16b.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/abs_quant.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/abs_quant_loop.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/augmented_cb_corr.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/bw_expand.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_construct.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_mem_energy.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_mem_energy_augmentation.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_mem_energy_calc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_search.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_search_core.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/cb_update_best_index.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/chebyshev.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/comp_corr.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/constants.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/create_augmented_vec.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/decode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/decode_residual.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/decoder_interpolate_lsf.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/do_plc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/encode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/energy_inverse.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/enh_upsample.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/enhancer.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/enhancer_interface.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/filtered_cb_vecs.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/frame_classify.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/gain_dequant.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/gain_quant.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/get_cd_vec.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/get_lsp_poly.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/get_sync_seq.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/hp_input.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/hp_output.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/ilbc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/index_conv_dec.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/index_conv_enc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/init_decode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/init_encode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/interpolate.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/interpolate_samples.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lpc_encode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsf_check.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsf_interpolate_to_poly_dec.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsf_interpolate_to_poly_enc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsf_to_lsp.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsf_to_poly.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/lsp_to_lsf.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/my_corr.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/nearest_neighbor.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/pack_bits.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/poly_to_lsf.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/poly_to_lsp.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/refiner.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/simple_interpolate_lsf.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/simple_lpc_analysis.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/simple_lsf_dequant.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/simple_lsf_quant.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/smooth.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/smooth_out_data.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/sort_sq.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/split_vq.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/state_construct.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/state_search.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/swap_bytes.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/unpack_bits.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/vq3.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/vq4.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/window32_w32.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/ilbc_c/xcorr_coef.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/g722_c/g722_decode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/g722_c/g722_encode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/g722_c/g722_interface.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/arith_routines.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/arith_routines_hist.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/arith_routines_logist.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/bandwidth_estimator.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/decode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/decode_bwe.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/decode_plc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/encode.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/entropy_coding.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/fft.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/filterbank_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/filterbanks.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/filters.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/initialize.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/isacfix.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/lattice.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/lattice_c.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/lpc_masking_model.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/lpc_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_estimator.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_estimator_c.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_filter.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_filter_c.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_gain_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/pitch_lag_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/spectrum_ar_model_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/transform.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_coding/isac_fix_c/transform_tables.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_processing/audio_processing_c/analog_agc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_processing/audio_processing_c/digital_agc.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_processing/audio_processing_c/noise_suppression.o
${WEBRTCBUILD}/obj/webrtc/modules/audio_processing/audio_processing_c/ns_core.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx/vp9_diamond_search_sad_avx.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/vp9_error_intrin_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/fwd_txfm_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/loopfilter_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/sad4d_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/sad_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/variance_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/variance_impl_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_avx2/vpx_subpixel_8t_intrin_avx2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_mmx/idct_blk_mmx.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_mmx/vp8_enc_stubs_mmx.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/idct_blk_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/denoising_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp8_enc_stubs_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp8_quantize_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp9_idct_intrin_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp9_dct_intrin_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp9_denoiser_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp9_highbd_block_error_intrin_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/vp9_quantize_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/avg_intrin_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/fwd_txfm_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/highbd_loopfilter_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/highbd_quantize_intrin_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/highbd_variance_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/inv_txfm_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/loopfilter_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/quantize_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/sum_squares_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse2/variance_sse2.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_sse4_1/quantize_sse4.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_ssse3/quantize_ssse3.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_ssse3/vp9_dct_ssse3.o
${WEBRTCBUILD}/obj/third_party/libvpx/libvpx_intrinsics_ssse3/vpx_subpixel_8t_intrin_ssse3.o)
